version: "2"
services:
  redis:
    image: redis
    ports: 
      - "6379"
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    image: mat_frontend:dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - NODE_ENV=development

